export interface WorskapacesProps {
  label: string;
  workspaces: any;
}

export const summariesWorkspace = [
  {
    label: 'Summary',
    foldersPath: ['Summary'],
    quickCollections: [],
  },
  {
    label: 'Shift',
    foldersPath: ['00 Shift'],
    quickCollections: [],
  },
  {
    label: 'Info',
    foldersPath: ['Info'],
    quickCollections: [
      'Info/Layouts/1 - HV and Beam Status per LumiSection',
      'Info/Layouts/2 - Run key set for DQM',
      'Info/Layouts/3 - HLT menu used',
      'Info/Layouts/4 - Version of CMSSW used',
      'Info/Layouts/5 - Global Tag used',
    ],
  },
  {
    label: 'Everything',
    foldersPath: [],
    quickCollections: [],
  },
];

const triggerWorkspace = [
  {
    label: 'L1T',
    foldersPath: ['L1T'],
    quickCollections: [
      'L1T/Layouts/Stage2-QuickCollection/00 - Calo Layer1 ECAL Input Occupancy',
      'L1T/Layouts/Stage2-QuickCollection/01 - Calo Layer1 HCAL Input Occupancy',
      'L1T/Layouts/Stage2-QuickCollection/02 - Calo Layer1 Input Link Errors and event mismatches',
      'L1T/Layouts/Stage2-QuickCollection/03 - uGMT MUON BX and Link vs BX',
      'L1T/Layouts/Stage2-QuickCollection/04 - uGMT MUON P_{T}',
      'L1T/Layouts/Stage2-QuickCollection/05 - uGMT MUON ETA',
      'L1T/Layouts/Stage2-QuickCollection/06 - uGMT MUON PHI',
      'L1T/Layouts/Stage2-QuickCollection/07 - uGMT MUON PHI ETA',
      'L1T/Layouts/Stage2-QuickCollection/08 - uGT Algoritm Trigger Bits (before prescale) vs Global BX Number',
      'L1T/Layouts/Stage2-QuickCollection/09 - uGT Algorithm Trigger Bits (after prescale) vs. Global BX Number',
      'L1T/Layouts/Stage2-QuickCollection/10 - uGT Algorithm Trigger Bits (after prescale) vs. BX Number in Event',
      'L1T/Layouts/Stage2-QuickCollection/11 - uGT Algorithm Trigger Bits (after prescale)',
      'L1T/Layouts/Stage2-QuickCollection/12 - Calo Layer2 Bx Occupancy distributions',
      'L1T/Layouts/Stage2-QuickCollection/13 - Calo Layer2 Central Jet Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/14 - Calo Layer2 Central Jets Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/15 - Calo Layer2 Forward Jet Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/16 - Calo Layer2 Forward Jet Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/17 - Calo Layer2 Isolated EG Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/18 - Calo Layer2 Isolated EG Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/19 - Calo Layer2 Non-Isolated EG Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/20 - Calo Layer2 Non-Isolated EG Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/21 - Calo Layer2 Isolated Tau Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/22 - Calo Layer2 Isolated Tau Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/23 - Calo Layer2 Non-Isolated Tau Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/24 - Calo Layer2 Non-Isolated Tau Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/25 - Calo Layer2 EtSum Bx Occupancy distribution',
      'L1T/Layouts/Stage2-QuickCollection/26 - Calo Layer2 ETT Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/27 - Calo Layer2 ETTEM Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/28 - Calo Layer2 HTT Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/29 - Calo Layer2 MET Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/30 - Calo Layer2 MET Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/31 - Calo Layer2 METHF Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/32 - Calo Layer2 METHF Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/33 - Calo Layer2 MHT Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/34 - Calo Layer2 MHT Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/35 - Calo Layer2 MHTHF Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/36 - Calo Layer2 MHTHF Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/37 - uGMT BMTF BX and Wedge vs BX',
      'L1T/Layouts/Stage2-QuickCollection/38 - BMTF Muon HW p_{T}',
      'L1T/Layouts/Stage2-QuickCollection/39 - uGMT BMTF HW Eta',
      'L1T/Layouts/Stage2-QuickCollection/40 - uGMT BMTF HW Phi',
      'L1T/Layouts/Stage2-QuickCollection/41 - uGMT BMTF HW vs Sign',
      'L1T/Layouts/Stage2-QuickCollection/42 - uGMT OMTF BX and Sector vs. BX',
      'L1T/Layouts/Stage2-QuickCollection/43 - uGMT OMTF HW p_{T}',
      'L1T/Layouts/Stage2-QuickCollection/44 - uGMT OMTF HW Eta',
      'L1T/Layouts/Stage2-QuickCollection/45 - uGMT OMTF HW Phi (top: positive, bottom: negative)',
      'L1T/Layouts/Stage2-QuickCollection/46 - uGMT OMTF HW Sign',
      'L1T/Layouts/Stage2-QuickCollection/47 - uGMT EMTF BX and Track vs BX',
      'L1T/Layouts/Stage2-QuickCollection/48 - uGMT EMTF Phi',
      'L1T/Layouts/Stage2-QuickCollection/49 - EMTF LCT Occupancy',
      'L1T/Layouts/Stage2-QuickCollection/50 - Calo TPG Link Errors and event mismatches (top: ECAL, bottom: HCAL)',
      'L1T/Layouts/Stage2-QuickCollection/51 - uGT CaloLayer2 Inputs Board 2-6 misMatch Ratios',
      'L1T/Layouts/Stage2-QuickCollection/52 - uGT Muon Inputs Board 2-6 misMatch Ratios',
      'L1T/Layouts/Stage2-QuickCollection/53 - uGMT Muon Copy 1-5 misMatch Ratios',
      'L1T/Layouts/Stage2-QuickCollection/54 - Input vs Output misMatch Ratios (clockwise from top left: uGT vs. uGMT, uGT vs. caloL2, uGMT vs. EMTF, uGMT vs. OMTF, uGMT vs. BMTF)',
      'L1T/Layouts/Stage2-QuickCollection/55 - uGMT Zero Suppression misMatch Ratio (left: all events, right: fat events)',
      'L1T/Layouts/Stage2-QuickCollection/56 - BMTF Zero Suppression misMatch Ratio (left: all events, right: fat events)',
    ],
  },
  {
    label: 'L1T2016EMU',
    foldersPath: ['L1T2016EMU'],
    quickCollections: [
      'L1TEMU/Layouts/Stage2-QuickCollection/00 - CaloTower Data-Emulator Status',
      "L1TEMU/Layouts/Stage2-QuickCollection/01 - uGMT Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/02 - BMTF Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/03 - OMTF Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/04 - EMTF Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/05 - Calo Layer2 High Level Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/06 - Calo Layer2 Jet Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/07 - Calo Layer2 EG Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/08 - Calo Layer2 Tau Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/09 - Calo Layer2 Energy Sum Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/10 - Calo Layer2 Problem Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/11 - uGT Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/12 - uGMT Intermediate Muon Data-Emulator misMatch ratio",
    ],
  },
  {
    label: 'L1T2016',
    foldersPath: ['L1T2016'],
    quickCollections: [
      'L1T/Layouts/Stage2-QuickCollection/00 - Calo Layer1 ECAL Input Occupancy',
      'L1T/Layouts/Stage2-QuickCollection/01 - Calo Layer1 HCAL Input Occupancy',
      'L1T/Layouts/Stage2-QuickCollection/02 - Calo Layer1 Input Link Errors and event mismatches',
      'L1T/Layouts/Stage2-QuickCollection/03 - uGMT MUON BX and Link vs BX',
      'L1T/Layouts/Stage2-QuickCollection/04 - uGMT MUON P_{T}',
      'L1T/Layouts/Stage2-QuickCollection/05 - uGMT MUON ETA',
      'L1T/Layouts/Stage2-QuickCollection/06 - uGMT MUON PHI',
      'L1T/Layouts/Stage2-QuickCollection/07 - uGMT MUON PHI ETA',
      'L1T/Layouts/Stage2-QuickCollection/08 - uGT Algoritm Trigger Bits (before prescale) vs Global BX Number',
      'L1T/Layouts/Stage2-QuickCollection/09 - uGT Algorithm Trigger Bits (after prescale) vs. Global BX Number',
      'L1T/Layouts/Stage2-QuickCollection/10 - uGT Algorithm Trigger Bits (after prescale) vs. BX Number in Event',
      'L1T/Layouts/Stage2-QuickCollection/11 - uGT Algorithm Trigger Bits (after prescale)',
      'L1T/Layouts/Stage2-QuickCollection/12 - Calo Layer2 Bx Occupancy distributions',
      'L1T/Layouts/Stage2-QuickCollection/13 - Calo Layer2 Central Jet Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/14 - Calo Layer2 Central Jets Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/15 - Calo Layer2 Forward Jet Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/16 - Calo Layer2 Forward Jet Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/17 - Calo Layer2 Isolated EG Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/18 - Calo Layer2 Isolated EG Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/19 - Calo Layer2 Non-Isolated EG Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/20 - Calo Layer2 Non-Isolated EG Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/21 - Calo Layer2 Isolated Tau Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/22 - Calo Layer2 Isolated Tau Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/23 - Calo Layer2 Non-Isolated Tau Et Eta vs Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/24 - Calo Layer2 Non-Isolated Tau Pt distribution',
      'L1T/Layouts/Stage2-QuickCollection/25 - Calo Layer2 EtSum Bx Occupancy distribution',
      'L1T/Layouts/Stage2-QuickCollection/26 - Calo Layer2 ETT Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/27 - Calo Layer2 ETTEM Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/28 - Calo Layer2 HTT Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/29 - Calo Layer2 MET Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/30 - Calo Layer2 MET Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/31 - Calo Layer2 METHF Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/32 - Calo Layer2 METHF Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/33 - Calo Layer2 MHT Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/34 - Calo Layer2 MHT Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/35 - Calo Layer2 MHTHF Et distribution',
      'L1T/Layouts/Stage2-QuickCollection/36 - Calo Layer2 MHTHF Phi distribution',
      'L1T/Layouts/Stage2-QuickCollection/37 - uGMT BMTF BX and Wedge vs BX',
      'L1T/Layouts/Stage2-QuickCollection/38 - BMTF Muon HW p_{T}',
      'L1T/Layouts/Stage2-QuickCollection/39 - uGMT BMTF HW Eta',
      'L1T/Layouts/Stage2-QuickCollection/40 - uGMT BMTF HW Phi',
      'L1T/Layouts/Stage2-QuickCollection/41 - uGMT BMTF HW vs Sign',
      'L1T/Layouts/Stage2-QuickCollection/42 - uGMT OMTF BX and Sector vs. BX',
      'L1T/Layouts/Stage2-QuickCollection/43 - uGMT OMTF HW p_{T}',
      'L1T/Layouts/Stage2-QuickCollection/44 - uGMT OMTF HW Eta',
      'L1T/Layouts/Stage2-QuickCollection/45 - uGMT OMTF HW Phi (top: positive, bottom: negative)',
      'L1T/Layouts/Stage2-QuickCollection/46 - uGMT OMTF HW Sign',
      'L1T/Layouts/Stage2-QuickCollection/47 - uGMT EMTF BX and Track vs BX',
      'L1T/Layouts/Stage2-QuickCollection/48 - uGMT EMTF Phi',
      'L1T/Layouts/Stage2-QuickCollection/49 - EMTF LCT Occupancy',
      'L1T/Layouts/Stage2-QuickCollection/50 - Calo TPG Link Errors and event mismatches (top: ECAL, bottom: HCAL)',
      'L1T/Layouts/Stage2-QuickCollection/51 - uGT CaloLayer2 Inputs Board 2-6 misMatch Ratios',
      'L1T/Layouts/Stage2-QuickCollection/52 - uGT Muon Inputs Board 2-6 misMatch Ratios',
      'L1T/Layouts/Stage2-QuickCollection/53 - uGMT Muon Copy 1-5 misMatch Ratios',
      'L1T/Layouts/Stage2-QuickCollection/54 - Input vs Output misMatch Ratios (clockwise from top left: uGT vs. uGMT, uGT vs. caloL2, uGMT vs. EMTF, uGMT vs. OMTF, uGMT vs. BMTF)',
      'L1T/Layouts/Stage2-QuickCollection/55 - uGMT Zero Suppression misMatch Ratio (left: all events, right: fat events)',
      'L1T/Layouts/Stage2-QuickCollection/56 - BMTF Zero Suppression misMatch Ratio (left: all events, right: fat events)',
    ],
  },
  {
    label: 'L1TEMU',
    foldersPath: ['L1TEMU'],
    quickCollections: [
      'L1TEMU/Layouts/Stage2-QuickCollection/00 - CaloTower Data-Emulator Status',
      "L1TEMU/Layouts/Stage2-QuickCollection/01 - uGMT Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/02 - BMTF Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/03 - OMTF Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/04 - EMTF Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/05 - Calo Layer2 High Level Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/06 - Calo Layer2 Jet Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/07 - Calo Layer2 EG Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/08 - Calo Layer2 Tau Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/09 - Calo Layer2 Energy Sum Data-Emulator Agreement Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/10 - Calo Layer2 Problem Summary",
      "L1TEMU/Layouts/Stage2-QuickCollection/11 - uGT Data-Emulator misMatch ratio",
      "L1TEMU/Layouts/Stage2-QuickCollection/12 - uGMT Intermediate Muon Data-Emulator misMatch ratio",
    ],
  },
  {
    label: 'HLT',
    foldersPath: ['HLT'],
    quickCollections: [
      'HLT/ObjectMonitor/MainShifter/Photon_pT',
      'HLT/ObjectMonitor/MainShifter/Muon_pT',
      'HLT/ObjectMonitor/MainShifter/Electron_pT',
      'HLT/ObjectMonitor/MainShifter/Jet_pT',
      'HLT/ObjectMonitor/MainShifter/JetAK8_Pt',
      'HLT/ObjectMonitor/MainShifter/JetAK8_mass',
      'HLT/ObjectMonitor/MainShifter/Tau_pT',
      'HLT/ObjectMonitor/MainShifter/Dimuon_LowMass',
      'HLT/ObjectMonitor/MainShifter/diMuon_Mass',
      'HLT/ObjectMonitor/MainShifter/di-Electron_Mass',
      'HLT/ObjectMonitor/MainShifter/alphaT',
      'HLT/ObjectMonitor/MainShifter/CaloMET_pT',
      'HLT/ObjectMonitor/MainShifter/CaloHT_pT',
      'HLT/ObjectMonitor/MainShifter/PFHT_pT',
      'HLT/ObjectMonitor/MainShifter/PFMET_pT',
      'HLT/ObjectMonitor/MainShifter/L2Muon_pT',
      'HLT/ObjectMonitor/MainShifter/L2NoBPTXMuon_pT',
      'HLT/ObjectMonitor/MainShifter/Rsq',
      'HLT/ObjectMonitor/MainShifter/mr',
      'HLT/ObjectMonitor/MainShifter/Muon_dxy',
      'HLT/ObjectMonitor/MainShifter/bJetCSVCalo',
      'HLT/ObjectMonitor/MainShifter/bJetCSVPF',
      'HLT/Tracking/iter2Merged/GeneralProperties/TrackPt_ImpactPoint_GenTk',
      'HLT/Tracking/pixelTracks/GeneralProperties/TrackPt_ImpactPoint_GenTk',
      'HLT/Tracking/iter2Merged/GeneralProperties/NumberOfTracksVsLS_GenTk',
      'HLT/Tracking/pixelTracks/GeneralProperties/NumberOfTracksVsLS_GenTk',
      'HLT/Tracking/iter2Merged/GeneralProperties/NumberOfRecHitsPerTrackVsLS_GenTk',
      'HLT/Tracking/pixelTracks/GeneralProperties/NumberOfRecHitsPerTrackVsLS_GenTk',
      'HLT/SiStrip/MechanicalView/TIB/TotalNumberOfClusterProfile__TIB',
      'HLT/Layouts/highestRate Summary',
    ],
  },
];

const trackerWorkspace = [
  {
    label: 'PixelPhase1',
    foldersPath: ['PixelPhase1'],
    quickCollections: [
      'PixelPhase1/Layouts/000 - PixelPhase1 ReportSummary: Layer or Disk vs subdet',
      'PixelPhase1/Layouts/00a - PixelPhase1 FED Occupancy vs Lumi Sections',
      'PixelPhase1/Layouts/00b - PixelPhase1_Error_Summary',
      'PixelPhase1/Layouts/01c - PixelPhase1 Cluster Size vs Cluster Eta',
      'PixelPhase1/Layouts/02 - PixelPhase1_Digi_ADC_Barrel',
      'PixelPhase1/Layouts/03 - PixelPhase1_Digi_ADC_Endcap',
      'PixelPhase1/Layouts/04 - PixelPhase1_Cluster_Number',
      'PixelPhase1/Layouts/05 - PixelPhase1_Cluster_Charge',
      'PixelPhase1/Layouts/06 - PixelPhase1_Cluster_Size',
      'PixelPhase1/Layouts/19 - PixelPhase1 Digis: Ladder vs Module barrel summary',
      'PixelPhase1/Layouts/20 - PixelPhase1 Clusters: Ladder vs Module barrel summary',
      'PixelPhase1/Layouts/24 - PixelPhase1 Cluster Position: Z vs Phi barrel summary',
      'PixelPhase1/Layouts/27 - PixelPhase1 Digis: BladePanel vs Disk endcap summary',
      'PixelPhase1/Layouts/28 - PixelPhase1 Clusters: BladePanel vs Disk endcap summary',
      'PixelPhase1/Layouts/30 - PixelPhase1 Cluster Position: X vs Y endcap summary',
      'PixelPhase1/Layouts/31 - PixelPhase1 Dead ROC Trends in barrel',
      'PixelPhase1/Layouts/32 - PixelPhase1 Dead ROC Trends in endcap',
      'PixelPhase1/Layouts/33 - ntracks',
      'PixelPhase1/Layouts/34 - Charge and size (on-track)',
      'PixelPhase1/Layouts/35a - Cluster charge (on-track) per Inner Ladders',
      'PixelPhase1/Layouts/35b - Cluster charge (on-track) per Outer Ladders',
      'PixelPhase1/Layouts/35c - Cluster charge (on-track) per Disk',
      'PixelPhase1/Layouts/36 - Cluster position (on-track) per PXLayer',
      'PixelPhase1/Layouts/37 - Cluster position (on-track) per Disk',
      'PixelPhase1/Layouts/40 - PixelPhase1 Residuals',
      'PixelPhase1/Layouts/41a - ClusterSize Vs Eta (on-track) inner',
      'PixelPhase1/Layouts/41b - ClusterSize Vs Eta (on-track) outer',
      'PixelPhase1/Layouts/42a - Cluster size (on-track) per Ladders',
      'PixelPhase1/Layouts/42b - Cluster size (on-track) per Disk',
      'PixelPhase1/Layouts/43a - Dead Channels per ROC per Barrel Layer',
      'PixelPhase1/Layouts/43b - Dead Channels per ROC per Forward Ring',
    ],
  },
  {
    label: 'Pixel',
    foldersPath: ['Pixel'],
    quickCollections: [],
  },
  {
    label: 'SiStrip',
    foldersPath: ['SiStrip', 'Tracking'],
    quickCollections: [
      'SiStrip/Layouts/00 - SiStrip ReportSummary',
      'SiStrip/Layouts/01 - FED-Detected Errors Summary',
      'SiStrip/Layouts/02 - FED-Detected Errors Trend',
      'SiStrip/Layouts/03 - # of Digi Trend',
      'SiStrip/Layouts/04 - # of Cluster Trend',
      'SiStrip/Layouts/05 - OnTrackCluster (StoN)',
      'SiStrip/Layouts/06 - OffTrackCluster (Total Number)',
      'SiStrip/Layouts/07 - Tracking ReportSummary',
      'SiStrip/Layouts/08 - Tracks (pp collisions)',
      'SiStrip/Layouts/09 - Tracks (Cosmic Tracking)',
      'SiStrip/Layouts/10 - Tracks (HI run)',
      'SiStrip/Layouts/11a - FED Errors vs FED ID',
      'SiStrip/Layouts/33 - Cluster & Digi occupancy per FED',
      'SiStrip/Layouts/34 - FED Errors Vs Id Vs Lumi',

    ],
  },
];

const calorimetersWorkspace = [
  {
    label: 'Ecal',
    foldersPath: ['Ecal', 'EcalBarrel', 'EcalEndcap', 'EcalCalibration'],
    quickCollections: [
      'Ecal/Layouts/00 Summary',
      'Ecal/Layouts/01 Occupancy Summary',
      'Ecal/Layouts/02 Calibration Summary',
    ],
  },
  {
    label: 'EcalPreshower',
    foldersPath: ['EcalPreshower'],
    quickCollections: [
      'EcalPreshower/Layouts/01-IntegritySummary-EcalPreshower',
      'EcalPreshower/Layouts/02-GoodRechitOccupancySummary-EcalPreshower',
      'EcalPreshower/Layouts/03-GoodRechitEnergySummary-EcalPreshower',
      'EcalPreshower/Layouts/04-ESTimingTaskSummary-EcalPreshower',
      'EcalPreshower/Layouts/05-ESGain-EcalPreshower',
      'EcalPreshower/Layouts/06-ES-Fiber-Error-Code',
    ],
  },
  {
    label: 'HCAL',
    foldersPath: ['Hcal', 'Hcal2'],
    quickCollections: [
      'Hcal/Layouts/00 Current Summary',
      'Hcal/Layouts/01 RAW Bad Quality',
      'Hcal/Layouts/02 RAW Bad Quality depth',
      'Hcal/Layouts/03 RAW Mismatches',
      'Hcal/Layouts/04 DIGI Missing 1LS',
      'Hcal/Layouts/05 DIGI Occupancy',
      'Hcal/Layouts/06 DIGI Occupancy Total',
      'Hcal/Layouts/07 DIGI Occupancy Cut',
      'Hcal/Layouts/08 DIGI Timing',
      'Hcal/Layouts/09 DIGI Total Charge',
      'Hcal/Layouts/10 DIGI Occupancy vs LS',
      'Hcal/Layouts/11 DIGI Amplitude vs LS',
      'Hcal/Layouts/12 RECO Energy',
      'Hcal/Layouts/13 RECO Occupancy',
      'Hcal/Layouts/14 RECO Occupancy Cut',
      'Hcal/Layouts/15 RECO Timing',
      'Hcal/Layouts/16 RECO HBHEabc Timing',
      'Hcal/Layouts/17 RECO Timing vs Energy',
      'Hcal/Layouts/18 TP Et Correlation',
      'Hcal/Layouts/19 TP Et Correlation Ratio',
      'Hcal/Layouts/20 TP Et Distribution',
      'Hcal/Layouts/21 TP Et Mismatches',
      'Hcal/Layouts/22 TP Et Missing',
      'Hcal/Layouts/23 TP Et Occupancy'
    ],
  },
  {
    label: 'HCALcalib',
    foldersPath: ['HcalCalib'],
    quickCollections: ['HcalCalib/Layouts/00 Current Summary',
      'HcalCalib/Layouts/01 Pedestal Mean',
      'HcalCalib/Layouts/02 Pedestal Mean by FED',
      'HcalCalib/Layouts/03 Pedestal RMS',
      'HcalCalib/Layouts/04 Pedestal RMS by FED',
      'HcalCalib/Layouts/05 Pedestal Mean DB Ref',
      'HcalCalib/Layouts/06 Pedestal Mean DB Ref by FED',
      'HcalCalib/Layouts/07 Pedestal RMS DB Ref',
      'HcalCalib/Layouts/08 Pedestal RMS DB Ref by FED',
      'HcalCalib/Layouts/09 Pedestal Mean Bad',
      'HcalCalib/Layouts/10 Pedestal Mean Bad by FED',
      'HcalCalib/Layouts/11 Pedestal RMS Bad',
      'HcalCalib/Layouts/12 Pedestal RMS Bad by FED',
      'HcalCalib/Layouts/13 Pedestal Missing',
      'HcalCalib/Layouts/14 Pedestal Missing by FED',
      'HcalCalib/Layouts/15 Pedestal Occupancy vs LS',
      'HcalCalib/Layouts/16 Missing vs LS',
      'HcalCalib/Layouts/17 Number of Bad Mean vs LS',
      'HcalCalib/Layouts/18 Number of Bad RMS vs LS'],
  },
  {
    label: 'Castor',
    foldersPath: ['Castor'],
    quickCollections: [
      'Castor/Layouts/01 - Map of frontend and readout errors',
      'Castor/Layouts/02 - Channel-wise timing',
      'Castor/Layouts/02b - Channel-wise timing (rms)',
      'Castor/Layouts/Digi/05 - DigiSize',
    ],
  },
];

const mounsWorkspace = [
  {
    label: 'CSC',
    foldersPath: ['CSC'],
    quickCollections: [
      'CSC/Layouts/00 Top Physics Efficiency',
      'CSC/Layouts/01 Station Physics Efficiency',
      'CSC/Layouts/02 EMU Summary/EMU Test01 - DDUs in Readout',
      'CSC/Layouts/02 EMU Summary/EMU Test03 - DDU Reported Errors',
      'CSC/Layouts/02 EMU Summary/EMU Test04 - DDU Format Errors',
      'CSC/Layouts/02 EMU Summary/EMU Test05 - DDU Inputs Status',
      'CSC/Layouts/02 EMU Summary/EMU Test06 - DDU Inputs in ERROR-WARNING State',
      'CSC/Layouts/02 EMU Summary/EMU Test08 - CSCs Reporting Data and Unpacked',
      'CSC/Layouts/02 EMU Summary/EMU Test10 - CSCs with Errors and Warnings (Fractions)',
      'CSC/Layouts/02 EMU Summary/EMU Test11 - CSCs without Data Blocks',
      'CSC/Layouts/06 Physics Efficiency - RecHits Minus',
      'CSC/Layouts/07 Physics Efficiency - RecHits Plus',
    ],
  },
  {
    label: 'DT',
    foldersPath: ['DT'],
    quickCollections: [
      'DT/Layouts/00-Summary/00-DataIntegritySummary',
      'DT/Layouts/00-Summary/00-ROChannelSummary',
      'DT/Layouts/00-Summary/01-OccupancySummary',
      'DT/Layouts/00-Summary/02-SegmentSummary',
      'DT/Layouts/00-Summary/03-TM_TriggerCorrFractionSummaryIn',
      'DT/Layouts/00-Summary/04-TM_Trigger2ndFractionSummaryIn',
      'DT/Layouts/00-Summary/05-NoiseChannelsSummary',
      'DT/Layouts/00-Summary/06-SynchNoiseSummary',
    ],
  },
  {
    label: 'RPC',
    foldersPath: ['RPC'],
    quickCollections: [
      'RPC/Layouts/01-Fatal_FED_Errors',
      'RPC/Layouts/02-RPC_Events',
      'RPC/Layouts/08-Barrel_Occupancy',
      'RPC/Layouts/09-Endcap_Occupancy',],
  },
  {
    label: 'GEM',
    foldersPath: ['GEM'],
    quickCollections: [
      'GEM/Layouts/Common/00 Summary',
      'GEM/Layouts/Common/01 AMC status positive endcap',
      'GEM/Layouts/Common/02 AMC status negative endcap',
      'GEM/Layouts/Common/03 GE-11L1 GEB input status',
      'GEM/Layouts/Common/04 GE-11L2 GEB input status',
      'GEM/Layouts/Common/05 GE+11L1 GEB input status',
      'GEM/Layouts/Common/06 GE+11L2 GEB input status',
      'GEM/Layouts/Common/07 GE-11L1 VFAT input status',
      'GEM/Layouts/Common/08 GE-11L2 VFAT input status',
      'GEM/Layouts/Common/09 GE+11L1 VFAT input status',
      'GEM/Layouts/Common/10 GE+11L2 VFAT input status',
      'GEM/Layouts/Common/11 GE-11L1 bunch crossing',
      'GEM/Layouts/Common/12 GE-11L2 bunch crossing',
      'GEM/Layouts/Common/13 GE+11L1 bunch crossing',
      'GEM/Layouts/Common/14 GE+11L2 bunch crossing',
      'GEM/Layouts/Common/15 GE-11L1 digi occupancy',
      'GEM/Layouts/Common/16 GE-11L2 digi occupancy',
      'GEM/Layouts/Common/17 GE+11L1 digi occupancy',
      'GEM/Layouts/Common/18 GE+11L2 digi occupancy',
      'GEM/Layouts/Common/19 GE-11L1 digi occupancy vs iEta',
      'GEM/Layouts/Common/20 GE-11L2 digi occupancy vs iEta',
      'GEM/Layouts/Common/21 GE+11L1 digi occupancy vs iEta',
      'GEM/Layouts/Common/22 GE+11L2 digi occupancy vs iEta',
      'GEM/Layouts/Common/23 GE-11L1 digi occupancy vs phi',
      'GEM/Layouts/Common/24 GE-11L2 digi occupancy vs phi',
      'GEM/Layouts/Common/25 GE+11L1 digi occupancy vs phi',
      'GEM/Layouts/Common/26 GE+11L2 digi occupancy vs phi',
      'GEM/Layouts/Common/27 GE-11L1 total number of strips per event',
      'GEM/Layouts/Common/28 GE-11L2 total number of strips per event',
      'GEM/Layouts/Common/29 GE+11L1 total number of strips per event',
      'GEM/Layouts/Common/30 GE+11L2 total number of strips per event',
      'GEM/Layouts/Common/31 GE-11L1 recHit occupancy',
      'GEM/Layouts/Common/32 GE-11L2 recHit occupancy',
      'GEM/Layouts/Common/33 GE+11L1 recHit occupancy',
      'GEM/Layouts/Common/34 GE+11L2 recHit occupancy',
      'GEM/Layouts/Common/35 GE-11L1 recHit occupancy vs iEta',
      'GEM/Layouts/Common/36 GE-11L2 recHit occupancy vs iEta',
      'GEM/Layouts/Common/37 GE+11L1 recHit occupancy vs iEta',
      'GEM/Layouts/Common/38 GE+11L2 recHit occupancy vs iEta',
      'GEM/Layouts/Common/39 GE-11L1 recHit occupancy vs phi',
      'GEM/Layouts/Common/40 GE-11L2 recHit occupancy vs phi',
      'GEM/Layouts/Common/41 GE+11L1 recHit occupancy vs phi',
      'GEM/Layouts/Common/42 GE+11L2 recHit occupancy vs phi',
      'GEM/Layouts/Common/43 GE-11L1 total number of recHits per event',
      'GEM/Layouts/Common/44 GE-11L2 total number of recHits per event',
      'GEM/Layouts/Common/45 GE+11L1 total number of recHits per event',
      'GEM/Layouts/Common/46 GE+11L2 total number of recHits per event',
      'GEM/Layouts/Common/47 GE-11L1 iEta 1 cluster size',
      'GEM/Layouts/Common/48 GE-11L1 iEta 2 cluster size',
      'GEM/Layouts/Common/49 GE-11L1 iEta 3 cluster size',
      'GEM/Layouts/Common/50 GE-11L1 iEta 4 cluster size',
      'GEM/Layouts/Common/51 GE-11L1 iEta 5 cluster size',
      'GEM/Layouts/Common/52 GE-11L1 iEta 6 cluster size',
      'GEM/Layouts/Common/53 GE-11L1 iEta 7 cluster size',
      'GEM/Layouts/Common/54 GE-11L1 iEta 8 cluster size',
      'GEM/Layouts/Common/55 GE-11L2 iEta 1 cluster size',
      'GEM/Layouts/Common/56 GE-11L2 iEta 2 cluster size',
      'GEM/Layouts/Common/57 GE-11L2 iEta 3 cluster size',
      'GEM/Layouts/Common/58 GE-11L2 iEta 4 cluster size',
      'GEM/Layouts/Common/59 GE-11L2 iEta 5 cluster size',
      'GEM/Layouts/Common/60 GE-11L2 iEta 6 cluster size',
      'GEM/Layouts/Common/61 GE-11L2 iEta 7 cluster size',
      'GEM/Layouts/Common/62 GE-11L2 iEta 8 cluster size',
      'GEM/Layouts/Common/63 GE+11L1 iEta 1 cluster size',
      'GEM/Layouts/Common/64 GE+11L1 iEta 2 cluster size',
      'GEM/Layouts/Common/65 GE+11L1 iEta 3 cluster size',
      'GEM/Layouts/Common/66 GE+11L1 iEta 4 cluster size',
      'GEM/Layouts/Common/67 GE+11L1 iEta 5 cluster size',
      'GEM/Layouts/Common/68 GE+11L1 iEta 6 cluster size',
      'GEM/Layouts/Common/69 GE+11L1 iEta 7 cluster size',
      'GEM/Layouts/Common/70 GE+11L1 iEta 8 cluster size',
      'GEM/Layouts/Common/71 GE+11L2 iEta 1 cluster size',
      'GEM/Layouts/Common/72 GE+11L2 iEta 2 cluster size',
      'GEM/Layouts/Common/73 GE+11L2 iEta 3 cluster size',
      'GEM/Layouts/Common/74 GE+11L2 iEta 4 cluster size',
      'GEM/Layouts/Common/75 GE+11L2 iEta 5 cluster size',
      'GEM/Layouts/Common/76 GE+11L2 iEta 6 cluster size',
      'GEM/Layouts/Common/77 GE+11L2 iEta 7 cluster size',
      'GEM/Layouts/Common/78 GE+11L2 iEta 8 cluster size',
    ]
  }
];

const cttpsWorspace = [
  {
    label: 'TrackingStrip',
    foldersPath: [
      'CTPPS/TrackingStrip',
      'CTPPS/common',
      'CTPPS/TrackingStrip/Layouts',
    ],
    quickCollections: [],
  },
  {
    label: 'TrackingPixel',
    foldersPath: [
      'CTPPS/TrackingPixel',
      'CTPPS/common',
      'CTPPS/TrackingPixel/Layouts',
    ],
    quickCollections: [],
  },
  {
    label: 'TimingDiamond',
    foldersPath: [
      'CTPPS/TimingDiamond',
      'CTPPS/common',
      'CTPPS/TimingDiamond/Layouts',
    ],
    quickCollections: [],
  },
  {
    label: 'TimingFastSilicon',
    foldersPath: [
      'CTPPS/TimingFastSilicon',
      'CTPPS/common',
      'CTPPS/TimingFastSilicon/Layouts',
    ],
    quickCollections: [],
  },
];

export const workspaces = [
  {
    label: 'Summaries',
    workspaces: summariesWorkspace,
  },
  {
    label: 'Trigger',
    workspaces: triggerWorkspace,
  },
  {
    label: 'Tracker',
    workspaces: trackerWorkspace,
  },
  {
    label: 'Calorimeters',
    workspaces: calorimetersWorkspace,
  },
  {
    label: 'Muons',
    workspaces: mounsWorkspace,
  },
  {
    label: 'CTPPS',
    workspaces: cttpsWorspace,
  },
];
